// Image to UUID decoder

const Decoder = (() => {
  const BRIGHTNESS_THRESHOLD = 200;

  // Load an image file into ImageData
  function loadImage(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const img = new Image();
        img.onload = () => {
          const canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0);
          resolve({
            imageData: ctx.getImageData(0, 0, img.width, img.height),
            width: img.width,
            height: img.height
          });
        };
        img.onerror = () => reject(new Error('Failed to load image'));
        img.src = reader.result;
      };
      reader.onerror = () => reject(new Error('Failed to read file'));
      reader.readAsDataURL(file);
    });
  }

  // Get pixel color at (x, y)
  function getPixel(imageData, x, y) {
    const idx = (Math.round(y) * imageData.width + Math.round(x)) * 4;
    return {
      r: imageData.data[idx],
      g: imageData.data[idx + 1],
      b: imageData.data[idx + 2],
      a: imageData.data[idx + 3]
    };
  }

  // Sample area around a point and return average color + filled status
  function sampleDot(imageData, cx, cy, radius) {
    const sampleRadius = Math.max(1, Math.floor(radius * 0.5));
    let rSum = 0, gSum = 0, bSum = 0, count = 0;

    for (let dy = -sampleRadius; dy <= sampleRadius; dy++) {
      for (let dx = -sampleRadius; dx <= sampleRadius; dx++) {
        if (dx * dx + dy * dy <= sampleRadius * sampleRadius) {
          const px = Math.round(cx + dx);
          const py = Math.round(cy + dy);
          if (px >= 0 && px < imageData.width && py >= 0 && py < imageData.height) {
            const p = getPixel(imageData, px, py);
            rSum += p.r;
            gSum += p.g;
            bSum += p.b;
            count++;
          }
        }
      }
    }

    if (count === 0) return { filled: false, color: '#E8E8E8' };

    const avgR = Math.round(rSum / count);
    const avgG = Math.round(gSum / count);
    const avgB = Math.round(bSum / count);

    const isEmptyDot = avgR > BRIGHTNESS_THRESHOLD &&
                       avgG > BRIGHTNESS_THRESHOLD &&
                       avgB > BRIGHTNESS_THRESHOLD;

    const color = '#' +
      avgR.toString(16).padStart(2, '0') +
      avgG.toString(16).padStart(2, '0') +
      avgB.toString(16).padStart(2, '0');

    return { filled: !isEmptyDot, color };
  }

  // Decode using known render config (for images generated by this app)
  function decodeWithConfig(imageData, config) {
    const step = config.dotRadius * 2 + config.dotGap;
    const gridCols = Encoder.GRID_COLS;
    const dataCells = Encoder.DATA_CELLS;

    const hexChars = [];

    // Read only the 32 data cells (skip the 4 padding cells)
    for (let i = 0; i < dataCells; i++) {
      const row = Math.floor(i / gridCols);
      const col = i % gridCols;
      const matrix = [[false, false], [false, false]];

      for (let dy = 0; dy < 2; dy++) {
        for (let dx = 0; dx < 2; dx++) {
          const cx = config.padding + (col * 2 + dx) * step + config.dotRadius;
          const cy = config.padding + (row * 2 + dy) * step + config.dotRadius;
          const sample = sampleDot(imageData, cx, cy, config.dotRadius);
          matrix[dy][dx] = sample.filled;
        }
      }

      hexChars.push(Encoder.matrixToHex(matrix));
    }

    const allHex = hexChars.join('');
    const segments = [
      allHex.slice(0, 8),
      allHex.slice(8, 12),
      allHex.slice(12, 16),
      allHex.slice(16, 20),
      allHex.slice(20, 32)
    ];

    return {
      uuid: UUID.assemble(segments),
      confidence: 1.0,
      segments,
      detectedColors: []
    };
  }

  // Full decode pipeline
  async function decode(file) {
    const { imageData, width, height } = await loadImage(file);

    // Check if image matches expected square dimensions
    const defaultConfig = CanvasRenderer.getDefaultConfig();
    const step = defaultConfig.dotRadius * 2 + defaultConfig.dotGap;
    const gridDots = Encoder.GRID_COLS * 2;
    const expectedSize = defaultConfig.padding * 2 + gridDots * step - defaultConfig.dotGap;

    const tolerance = 4;
    if (Math.abs(width - expectedSize) <= tolerance &&
        Math.abs(height - expectedSize) <= tolerance) {
      try {
        return decodeWithConfig(imageData, defaultConfig);
      } catch (e) {
        // Fall through
      }
    }

    throw new Error(
      'Could not decode UUID from this image. ' +
      'Expected a ' + expectedSize + 'x' + expectedSize + 'px square image generated by this app.'
    );
  }

  return { decode };
})();
